databases:
  - name: amine_database
    databaseName: amine_database_xdsy
    user: amine_database_xdsy_user

services:
  - type: web
    name: budget-expense-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amine_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false